# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  lint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: mkdir lint
      - run: swiftlint lint --strict --reporter junit | tee lint/result.xml
      - store_artifacts:
          path: lint
      - store_test_results:
          path: lint
  test:
    macos:
      xcode: "10.1.0"
    environment:
      BREW_PATH: /usr/local/Homebrew
      BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - restore_cache:
          key: v{{ .Environment.CACHE_VERSION }}-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Decode certficates
          command: base64 -D -o $CERTIFICATE_PATH <<< $CERTIFICATE
      - run:
          name: Install dependencies
          command: carthage bootstrap --platform macos
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: "./test_output"
      - store_artifacts:
          path: "./test_output"

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
